//Select Id, FirstName, LastName from Contacts
//run this query and store the result into List<Contact> 

// List<Contact> conList1 = [Select Id, FirstName, LastName, Email from Contact];

// for(Contact each : conList1){
//     System.debug(each);
// }

// Contact c1=[Select Id, FirstName, LastName from Contact where FirstName=null];

// System.debug(c1);

// c1.FirstName='update';

// update c1;

// System.debug(c1);

